import { createReadStream } from "node:fs";
import { createInterface } from "node:readline";
import { basename, dirname } from "node:path";
import type { CachedSession, Session, Turn } from "./types.js";

/** Longest excerpt quoted as evidence before it is cut with "…". */
export const EXCERPT_MAX = 400;

/**
 * Claude Code writes ~/.claude/projects/<encoded-cwd>/<session>.jsonl.
 * The format is undocumented and changes; this parser is deliberately
 * tolerant: unknown lines are counted and skipped, never fatal.
 */

const NOISE_PATTERNS = [
  /^<command-name>/,
  /^<local-command-stdout>/,
  /^<local-command-caveat>/,
  /^<system-reminder>/,
  /^Caveat: The messages below were generated by the user while running local commands/,
  /^<bash-input>/,
  /^<bash-stdout>/,
  /^<ide_/,
];

const INTERRUPT_MARKER = /\[Request interrupted by user[^\]]*\]\s*/i;

function decodeProject(file: string): string {
  // Encoded dir looks like "-Users-danny-code-alkimi-docs"; best-effort decode.
  const dir = basename(dirname(file));
  if (dir.startsWith("-")) return dir.replace(/-/g, "/");
  return dir;
}

function textOf(content: unknown): { text: string; tools: string[]; toolResultOnly: boolean } {
  if (typeof content === "string") return { text: content, tools: [], toolResultOnly: false };
  if (!Array.isArray(content)) return { text: "", tools: [], toolResultOnly: false };
  const texts: string[] = [];
  const tools: string[] = [];
  let sawText = false;
  let sawToolResult = false;
  for (const block of content) {
    if (!block || typeof block !== "object") continue;
    const b = block as Record<string, unknown>;
    if (b.type === "text" && typeof b.text === "string") {
      texts.push(b.text);
      sawText = true;
    } else if (b.type === "tool_use" && typeof b.name === "string") {
      tools.push(b.name);
    } else if (b.type === "tool_result") {
      sawToolResult = true;
    }
  }
  return { text: texts.join("\n"), tools, toolResultOnly: sawToolResult && !sawText };
}

export async function parseTranscript(file: string, fromLine = 0): Promise<Session> {
  const rl = createInterface({ input: createReadStream(file, "utf8"), crlfDelay: Infinity });
  const turns: Turn[] = [];
  let unknownEvents = 0;
  let lineNo = 0;
  let sessionId = basename(file, ".jsonl");
  let project = decodeProject(file);
  let prevAssistantInterrupted = false;

  for await (const raw of rl) {
    lineNo++;
    if (lineNo <= fromLine) continue;
    const line = raw.trim();
    if (!line) continue;
    let ev: Record<string, unknown>;
    try {
      ev = JSON.parse(line);
    } catch {
      unknownEvents++;
      continue;
    }
    if (typeof ev.sessionId === "string") sessionId = ev.sessionId;
    if (typeof ev.cwd === "string") project = ev.cwd;

    const type = ev.type;
    if (type !== "user" && type !== "assistant") {
      unknownEvents++;
      continue;
    }
    const msg = (ev.message ?? {}) as Record<string, unknown>;
    const { text, tools, toolResultOnly } = textOf(msg.content);
    const meta = ev.isMeta === true || NOISE_PATTERNS.some((p) => p.test(text.trimStart()));
    const interrupted = INTERRUPT_MARKER.test(text);
    const ts = typeof ev.timestamp === "string" ? Date.parse(ev.timestamp) || 0 : 0;

    turns.push({
      id: `${sessionId}:${typeof ev.uuid === "string" ? ev.uuid : lineNo}`,
      sessionId,
      project,
      file,
      line: lineNo,
      role: type,
      ts,
      text: text.replace(INTERRUPT_MARKER, "").trim(),
      toolUses: tools,
      toolResult: toolResultOnly,
      interrupted: interrupted || (type === "user" && prevAssistantInterrupted),
      meta,
    });
    prevAssistantInterrupted = type === "assistant" && interrupted;
  }
  return { sessionId, project, file, turns, unknownEvents };
}

function isHuman(t: Turn): boolean {
  return t.role === "user" && !t.toolResult && !t.meta && t.text.length > 0;
}

/** Genuine human turns: not tool results, not meta/slash-command noise, non-empty. */
export function humanTurns(session: Session): Turn[] {
  return session.turns.filter(isHuman);
}

/**
 * Shrinks a session for the parse cache. Only human turn text is read in full; other turns'
 * text only feeds evidence excerpts, so one char past EXCERPT_MAX keeps the "…" truncation exact.
 */
export function compactSession(session: Session): CachedSession {
  return {
    ...session,
    turns: session.turns.map((t) => {
      const { id, sessionId, project, file: _file, text, ...rest } = t;
      return {
        ...rest,
        key: id.slice(sessionId.length + 1),
        text: isHuman(t) ? text : text.slice(0, EXCERPT_MAX + 1),
        ...(sessionId !== session.sessionId && { sessionId }),
        ...(project !== session.project && { project }),
      };
    }),
  };
}

export function expandSession(cached: CachedSession): Session {
  return {
    ...cached,
    turns: cached.turns.map(({ key, sessionId = cached.sessionId, project = cached.project, ...rest }) => ({
      ...rest,
      id: `${sessionId}:${key}`,
      sessionId,
      project,
      file: cached.file,
    })),
  };
}
